import type { AutonomousBuild, FactoryJob, SubmitAutonomousBuildInput } from './types';

function cfg(){const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY||'';if(!url||!key)throw new Error('Supabase autonomy store is not configured');return{url,key}}
async function sb<T>(path:string,method='GET',body?:unknown,prefer='return=representation'){const {url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const text=await r.text();let data:T|null=null;try{data=text?JSON.parse(text) as T:null}catch{data=text as T}if(!r.ok)throw new Error(`Supabase ${method} ${path} failed ${r.status}: ${text.slice(0,500)}`);return data}
const e=encodeURIComponent;

export async function submitBuild(input:SubmitAutonomousBuildInput,actor:string,key:string){const rows=await sb<Array<{submit_autonomous_build?:unknown;result?:unknown}>>('rpc/submit_autonomous_build','POST',{p_idempotency_key:key,p_title:input.title,p_mission:input.mission,p_requested_outputs:input.requestedOutputs||[],p_source_manifest:input.sourceManifest||{},p_priority:input.priority||5,p_browser_mode:input.browserMode||'auto',p_max_concurrency:input.maxConcurrency||8,p_created_by:actor});const raw=rows?.[0] as Record<string,unknown>|undefined;return (raw?.result||raw?.submit_autonomous_build||raw) as {build:AutonomousBuild;job:FactoryJob|null;duplicate:boolean}}
export async function listBuilds(limit=50){return await sb<AutonomousBuild[]>(`autonomous_builds?select=*&order=created_at.desc&limit=${Math.max(1,Math.min(200,limit))}`)||[]}
export async function getBuild(id:string){const rows=await sb<AutonomousBuild[]>(`autonomous_builds?id=eq.${e(id)}&select=*&limit=1`)||[];if(!rows[0])throw new Error(`Build ${id} not found`);return rows[0]}
export async function getEvents(id:string){return await sb<Record<string,unknown>[]>(`autonomous_build_events?build_id=eq.${e(id)}&select=*&order=created_at.desc&limit=200`)||[]}
export async function getJobs(id:string){return await sb<FactoryJob[]>(`factory_jobs?queue_name=eq.autonomy&input_payload->>build_id=eq.${e(id)}&select=*&order=created_at.desc&limit=200`)||[]}
export async function patchBuild(id:string,patch:Record<string,unknown>){const rows=await sb<AutonomousBuild[]>(`autonomous_builds?id=eq.${e(id)}`,'PATCH',{...patch,updated_at:new Date().toISOString()})||[];if(!rows[0])throw new Error(`Build ${id} update failed`);return rows[0]}
export async function event(id:string,type:string,message:string,data:Record<string,unknown>={}){const rows=await sb<Record<string,unknown>[]>('autonomous_build_events','POST',{build_id:id,event_type:type,message,data});return rows?.[0]}
export async function enqueue(buildId:string,jobType:string,title:string,key:string,payload:Record<string,unknown>={},priority=5){try{const rows=await sb<FactoryJob[]>('factory_jobs','POST',{job_type:jobType,queue_name:'autonomy',title,status:'queued',priority,idempotency_key:key,input_payload:{build_id:buildId,...payload}});return rows?.[0]||null}catch(err){if(String(err).includes('409'))return null;throw err}}
export async function claim(worker:string,limit=4){return await sb<FactoryJob[]>('rpc/claim_autonomy_jobs','POST',{p_worker_id:worker,p_limit:limit})||[]}
export async function completeJob(id:string){return await sb<FactoryJob[]>(`factory_jobs?id=eq.${e(id)}`,'PATCH',{status:'completed',completed_at:new Date().toISOString(),lease_owner:null,lease_expires_at:null,last_error:null})}
export async function failJob(job:FactoryJob,error:string){const terminal=(job.attempt_count||0)>=(job.max_attempts||3);return await sb<FactoryJob[]>(`factory_jobs?id=eq.${e(job.id)}`,'PATCH',{status:terminal?'failed':'queued',last_error:error.slice(0,1500),lease_owner:null,lease_expires_at:null})}
export async function cancelBuild(id:string,actor:string){const rows=await sb<Array<Record<string,unknown>>>('rpc/cancel_autonomous_build','POST',{p_build_id:id,p_actor_id:actor});return rows?.[0]}
export async function retryBuild(id:string,actor:string){const rows=await sb<Array<Record<string,unknown>>>('rpc/retry_autonomous_build','POST',{p_build_id:id,p_actor_id:actor});return rows?.[0]}
export async function createIngestion(buildId:string,title:string,sources:unknown[],actor:string){const id=crypto.randomUUID();const rows=await sb<Record<string,unknown>[]>('autonomy_ingestion_manifests','POST',{id,build_id:buildId,title,status:'QUEUED',source_count:sources.length,sources,created_by:actor});await enqueue(buildId,'bulk-ingest',`Bulk ingest: ${title}`,`bulk-ingest:${id}`,{manifest_id:id});return rows?.[0]}
export async function getIngestion(id:string){const rows=await sb<Record<string,unknown>[]>(`autonomy_ingestion_manifests?id=eq.${e(id)}&select=*&limit=1`)||[];if(!rows[0])throw new Error(`Ingestion ${id} not found`);return rows[0]}
export async function patchIngestion(id:string,patch:Record<string,unknown>){return await sb<Record<string,unknown>[]>(`autonomy_ingestion_manifests?id=eq.${e(id)}`,'PATCH',{...patch,updated_at:new Date().toISOString()})}
export async function publishCompleted(build:AutonomousBuild){return await sb<Record<string,unknown>[]>('autonomy_completed_projects?on_conflict=build_id','POST',{build_id:build.id,title:build.title,github_repo_url:build.github_repo_url,github_pr_url:build.github_pr_url,vercel_project_id:build.vercel_project_id,preview_url:build.preview_url,validation_score:build.validation_score,artifact_manifest:build.artifact_manifest,completion_summary:build.upstream_status},'resolution=merge-duplicates,return=representation')}
