import type { AutonomousBuild, FactoryJob, UpstreamSwarmStatus } from './types';
import { claim, completeJob, enqueue, event, failJob, getBuild, getIngestion, patchBuild, patchIngestion, publishCompleted } from './build-store';
import { callUpstreamMcp, getUpstreamSwarmStatus, startUpstreamSwarm } from './upstream-mcp';
import { progressForStage, upstreamHasFailed, upstreamIsComplete } from './state-machine';

const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null;
async function root(job:FactoryJob,b:AutonomousBuild){const sources=Array.isArray(b.source_manifest?.sources)?b.source_manifest.sources:[];if(sources.length){await enqueue(b.id,'bulk-ingest',`Bulk ingest: ${b.title}`,`bulk-ingest:${b.id}`,{sources});await patchBuild(b.id,{status:'RUNNING',current_stage:'INGESTION',progress:15})}else{await enqueue(b.id,'autonomous-build-start',`Start swarm: ${b.title}`,`swarm-start:${b.id}`);await patchBuild(b.id,{status:'RUNNING',current_stage:'PLANNING',progress:25})}await event(b.id,'autonomy.root.accepted','Root build packet accepted.');return{accepted:true}}
async function ingest(job:FactoryJob,b:AutonomousBuild){const sources=Array.isArray(job.input_payload?.sources)?job.input_payload?.sources:[];const result=await callUpstreamMcp('bulk_ingest',{build_id:b.id,title:b.title,sources,resumable:true,deduplicate:true,preserve_provenance:true});await enqueue(b.id,'autonomous-build-start',`Start swarm: ${b.title}`,`swarm-start:${b.id}`);await patchBuild(b.id,{current_stage:'PLANNING',progress:25});await event(b.id,'autonomy.ingestion.completed','Bulk ingestion completed.',{result});return result}
async function start(job:FactoryJob,b:AutonomousBuild){const r=await startUpstreamSwarm(b);const runId=str((r as any).run_id)||str((r as any).id);if(!runId)throw new Error('run_swarm returned no durable run ID');await patchBuild(b.id,{status:'RUNNING',current_stage:'SWARM',progress:40,upstream_run_id:runId,upstream_status:r,last_error:null});await enqueue(b.id,'autonomous-build-monitor',`Monitor swarm: ${b.title}`,`swarm-monitor:${b.id}`,{run_id:runId});await event(b.id,'autonomy.swarm.started','Recursive parallel swarm started.',{run_id:runId});return r}
async function monitor(job:FactoryJob,b:AutonomousBuild){const runId=str(job.input_payload?.run_id)||b.upstream_run_id;if(!runId)throw new Error('Monitor packet has no run ID');const s=await getUpstreamSwarmStatus(runId);if(upstreamHasFailed(s.status)){await patchBuild(b.id,{status:'FAILED',last_error:`Upstream swarm ${String(s.status)}`,upstream_status:s});throw new Error(`Upstream swarm ${String(s.status)}`)}if(!upstreamIsComplete(s.status)){await patchBuild(b.id,{status:'RUNNING',current_stage:'BUILD',progress:progressForStage('BUILD',s.progress),upstream_status:s});await enqueue(b.id,'autonomous-build-monitor',`Monitor swarm: ${b.title}`,`swarm-monitor:${b.id}:${Math.floor(Date.now()/300000)}`,{run_id:runId});return{pending:true,status:s}}const patch:any={status:'RUNNING',current_stage:'FINALIZATION',progress:97,upstream_status:s,github_repo_url:str(s.github_repo_url)||str(s.result?.github_repo_url),github_branch:str(s.github_branch)||str(s.result?.github_branch),github_pr_url:str(s.github_pr_url)||str(s.result?.github_pr_url),vercel_project_id:str(s.vercel_project_id)||str(s.result?.vercel_project_id),vercel_project_url:str(s.vercel_project_url)||str(s.result?.vercel_project_url),preview_url:str(s.preview_url)||str(s.result?.preview_url),validation_score:typeof s.validation_score==='number'?s.validation_score:s.result?.validation_score,artifact_manifest:Array.isArray(s.artifacts)?s.artifacts:[]};await patchBuild(b.id,patch);await enqueue(b.id,'autonomous-build-finalize',`Finalize: ${b.title}`,`finalize:${b.id}`);return{complete:true,status:s}}
async function finalize(job:FactoryJob,b:AutonomousBuild){const current=await getBuild(b.id);const missing=[!current.github_repo_url?'github_repo_url':null,!current.vercel_project_id?'vercel_project_id':null,!current.preview_url?'preview_url':null,typeof current.validation_score!=='number'?'validation_score':null].filter(Boolean);if(missing.length){await patchBuild(b.id,{status:'NEEDS_INPUT',last_error:`Completion evidence missing: ${missing.join(', ')}`});return{complete:false,missing}}const done=await patchBuild(b.id,{status:'COMPLETE',current_stage:'COMPLETE',progress:100,completed_at:new Date().toISOString(),last_error:null});await publishCompleted(done);await event(b.id,'autonomy.completed','GitHub repository, Vercel project, preview, and validation evidence are complete.');return{complete:true}}
export async function dispatchControlledAutonomy(worker=`autonomy-${crypto.randomUUID()}`,limit=4){const jobs=await claim(worker,limit);const results=[];for(const job of jobs){try{const id=str(job.input_payload?.build_id);if(!id)throw new Error('Job missing build_id');const b=await getBuild(id);if(['CANCELLED','COMPLETE'].includes(b.status)){await completeJob(job.id);results.push({job_id:job.id,state:'SKIPPED'});continue}let output;switch(job.job_type){case'autonomous-build-root':output=await root(job,b);break;case'bulk-ingest':output=await ingest(job,b);break;case'autonomous-build-start':output=await start(job,b);break;case'autonomous-build-monitor':output=await monitor(job,b);break;case'autonomous-build-finalize':output=await finalize(job,b);break;default:throw new Error(`Unsupported autonomy job ${job.job_type}`)}await completeJob(job.id);results.push({job_id:job.id,state:'COMPLETED',output})}catch(err){const message=err instanceof Error?err.message:String(err);await failJob(job,message);results.push({job_id:job.id,state:'FAILED',error:message})}}return{worker_id:worker,claimed:jobs.length,results}}
