import { Template, Playbook } from './types'

export const TEMPLATES: Template[] = [
  // ── LANDING PAGES ──────────────────────────────────────────
  {
    id: 'template-landing',
    name: 'Lead-Gen Landing Page',
    category: 'landing',
    bestFor: 'Single-offer campaigns — capture leads fast',
    requiredPages: ['Home'],
    defaultSections: ['Hero', 'Problem Statement', 'Solution', 'Social Proof', 'CTA Section', 'FAQ'],
    ctaStrategy: 'Email capture with lead magnet offer',
    leadFields: ['First Name', 'Email', 'Phone'],
    validationChecks: ['CTA visibility', 'Mobile responsiveness', 'Form conversion', 'Trust proof present'],
    socialAssets: ['Hero image', 'Quote graphic', 'CTA banner'],
    recommendedWorkflow: 'simple-lead-capture',
    estimatedComplexity: 'simple',
    estimatedLaunchTime: '3–5 days',
    description: 'Single-page, high-conversion landing page optimized for capturing email leads with a compelling offer above the fold.',
  },
  {
    id: 'template-vsl',
    name: 'Video Sales Letter (VSL) Page',
    category: 'landing',
    bestFor: 'High-ticket offers that need explanation before buy',
    requiredPages: ['Landing'],
    defaultSections: ['Video Hero', 'Problem Agitation', 'Solution Reveal', 'Proof Stack', 'Urgency CTA', 'FAQ'],
    ctaStrategy: 'Watch video → application form or checkout',
    leadFields: ['Name', 'Email', 'Phone'],
    validationChecks: ['Video loads on mobile', 'CTA appears after video', 'Form submits'],
    socialAssets: ['Thumbnail image', 'Social proof screenshot', 'Results graphic'],
    recommendedWorkflow: 'simple-lead-capture',
    estimatedComplexity: 'simple',
    estimatedLaunchTime: '3–5 days',
    description: 'Video-first landing page designed to sell high-ticket services through persuasive video storytelling.',
  },
  {
    id: 'template-webinar',
    name: 'Webinar Registration Page',
    category: 'landing',
    bestFor: 'Coaches, consultants, and SaaS products running webinars',
    requiredPages: ['Registration', 'Confirmation'],
    defaultSections: ['Host intro', 'What you\'ll learn', 'Registration form', 'Social proof', 'Countdown timer'],
    ctaStrategy: 'Register for free webinar',
    leadFields: ['Name', 'Email', 'Phone'],
    validationChecks: ['Registration form works', 'Confirmation email sends', 'Countdown accurate'],
    socialAssets: ['Host headshot', 'Webinar cover graphic', 'Social share card'],
    recommendedWorkflow: 'simple-lead-capture',
    estimatedComplexity: 'simple',
    estimatedLaunchTime: '2–3 days',
    description: 'Urgency-driven webinar registration page built to convert cold traffic into hot leads with a free educational event.',
  },

  // ── BUSINESS ───────────────────────────────────────────────
  {
    id: 'template-business',
    name: 'Premium Business Website',
    category: 'business',
    bestFor: 'Established businesses wanting to showcase authority',
    requiredPages: ['Home', 'About', 'Services', 'Portfolio', 'Contact'],
    defaultSections: ['Hero', 'Services Grid', 'Case Studies', 'Team', 'Testimonials', 'Contact Form'],
    ctaStrategy: 'Schedule consultation or request proposal',
    leadFields: ['Name', 'Email', 'Company', 'Phone', 'Message'],
    validationChecks: ['All pages load', 'Contact forms work', 'Portfolio displays correctly', 'Navigation clear'],
    socialAssets: ['Service graphics', 'Team photos', 'Case study previews'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '2–3 weeks',
    description: 'Multi-page professional website showcasing business expertise, case studies, and team credibility.',
  },
  {
    id: 'template-agency',
    name: 'Creative Agency Portfolio',
    category: 'business',
    bestFor: 'Marketing agencies, design studios, creative teams',
    requiredPages: ['Home', 'Work', 'Services', 'About', 'Contact'],
    defaultSections: ['Full-screen hero', 'Case study grid', 'Services list', 'Credentials', 'Process', 'CTA'],
    ctaStrategy: 'Book a strategy call or request a proposal',
    leadFields: ['Name', 'Email', 'Company', 'Budget Range', 'Project Type'],
    validationChecks: ['Portfolio items load', 'Hover effects work', 'Video plays correctly', 'Forms submit'],
    socialAssets: ['Portfolio previews', 'Awards/recognition', 'Client logos'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '2–3 weeks',
    description: 'Bold, visual portfolio site for creative agencies to showcase work and attract premium clients.',
  },

  // ── LOCAL SERVICE ──────────────────────────────────────────
  {
    id: 'template-local',
    name: 'Local Service Website',
    category: 'local-service',
    bestFor: 'Home services, contractors, and local businesses',
    requiredPages: ['Home', 'Services', 'Service Areas', 'Testimonials', 'Contact'],
    defaultSections: ['Hero with service focus', 'Service listings', 'Service areas', 'Testimonials', 'Before/After gallery', 'Quick contact'],
    ctaStrategy: 'Call to action + phone click-to-call',
    leadFields: ['Name', 'Email', 'Phone', 'Service Type', 'Zip Code'],
    validationChecks: ['Phone number clickable', 'Service areas accurate', 'Testimonials display', 'Mobile optimized'],
    socialAssets: ['Before/after grid', 'Service icons', 'Local area map'],
    recommendedWorkflow: 'simple-lead-capture',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '1–2 weeks',
    description: 'Website for local service providers with location targeting, before/after galleries, and mobile-first lead capture.',
  },
  {
    id: 'template-flooring',
    name: 'Flooring & Polishing Company',
    category: 'local-service',
    bestFor: 'Epoxy flooring, concrete polishing, floor coatings, tile installers',
    requiredPages: ['Home', 'Services', 'Gallery', 'Service Areas', 'Testimonials', 'Free Quote'],
    defaultSections: ['Dramatic before/after hero', 'Flooring systems grid', 'Gallery with filter', 'Service areas map', 'Reviews wall', 'Free quote form'],
    ctaStrategy: 'Get Free Estimate + Phone call',
    leadFields: ['Name', 'Email', 'Phone', 'Property Address', 'Floor Type', 'Square Footage', 'Timeline'],
    validationChecks: ['Gallery loads correctly', 'Phone click-to-call works', 'Estimate form submits', 'Mobile hero image'],
    socialAssets: ['Before/after comparison sliders', 'Product system cards', 'Service area pin map'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '1–2 weeks',
    description: 'Built specifically for flooring and polishing companies — showcases floor systems, dramatic before/after results, and drives free estimate requests.',
  },
  {
    id: 'template-roofing',
    name: 'Roofing Contractor Website',
    category: 'local-service',
    bestFor: 'Residential and commercial roofing companies',
    requiredPages: ['Home', 'Roofing Services', 'Financing', 'Service Areas', 'Reviews', 'Free Inspection'],
    defaultSections: ['Storm damage CTA hero', 'Roofing types', 'Financing options', 'Certifications', 'Reviews', 'Inspection form'],
    ctaStrategy: 'Schedule free roof inspection + Emergency call',
    leadFields: ['Name', 'Phone', 'Email', 'Address', 'Roof Type', 'Insurance Claim?'],
    validationChecks: ['Emergency number prominent', 'Financing page works', 'Inspection form submits', 'Mobile first'],
    socialAssets: ['Roof damage before/after', 'Certification badges', 'Storm damage urgency banner'],
    recommendedWorkflow: 'simple-lead-capture',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '1–2 weeks',
    description: 'High-urgency roofing contractor site built for emergency traffic, insurance claims, and free inspection lead generation.',
  },
  {
    id: 'template-hvac',
    name: 'HVAC & Mechanical Services',
    category: 'local-service',
    bestFor: 'HVAC, plumbing, electrical, and mechanical contractors',
    requiredPages: ['Home', 'Services', 'Maintenance Plans', 'Service Areas', 'Emergency Service', 'Contact'],
    defaultSections: ['24/7 hero', 'Service menu', 'Maintenance plan comparison', 'Trust badges', 'Customer reviews', 'Emergency CTA'],
    ctaStrategy: '24/7 emergency call + Schedule service',
    leadFields: ['Name', 'Phone', 'Email', 'Address', 'Service Type', 'Urgency Level'],
    validationChecks: ['24/7 phone number prominent', 'Service areas correct', 'Maintenance plan displays', 'Mobile call button'],
    socialAssets: ['Equipment graphics', 'Certification seals', 'Emergency service banner'],
    recommendedWorkflow: 'simple-lead-capture',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '1–2 weeks',
    description: 'Urgency-focused site for HVAC and mechanical contractors with 24/7 emergency service emphasis and maintenance plan upsells.',
  },
  {
    id: 'template-landscaping',
    name: 'Landscaping & Outdoor Living',
    category: 'local-service',
    bestFor: 'Landscaping, lawn care, hardscaping, outdoor living design',
    requiredPages: ['Home', 'Services', 'Portfolio', 'Service Areas', 'Seasonal Specials', 'Free Quote'],
    defaultSections: ['Stunning outdoor hero', 'Service categories', 'Photo portfolio', 'Seasonal packages', 'Customer results', 'Quote form'],
    ctaStrategy: 'Get free landscape design quote',
    leadFields: ['Name', 'Email', 'Phone', 'Property Address', 'Project Type', 'Budget Range', 'Start Date'],
    validationChecks: ['Portfolio images load', 'Quote form submits', 'Service areas display', 'Mobile gallery'],
    socialAssets: ['Portfolio grid', 'Seasonal promo graphics', 'Before/after transformations'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '1–2 weeks',
    description: 'Visual-first landscaping site built around stunning portfolio photography, seasonal offers, and online quote generation.',
  },

  // ── PORTAL ─────────────────────────────────────────────────
  {
    id: 'template-portal',
    name: 'Client Portal',
    category: 'portal',
    bestFor: 'Providing clients access to project information',
    requiredPages: ['Dashboard', 'Projects', 'Messages', 'Documents', 'Settings'],
    defaultSections: ['Project summary', 'File uploads', 'Timeline', 'Messages', 'Invoice/Payment'],
    ctaStrategy: 'Action within portal (upload, approve, pay)',
    leadFields: [],
    validationChecks: ['Authentication works', 'File downloads work', 'Messages send', 'Data persists'],
    socialAssets: [],
    recommendedWorkflow: 'full-client-portal',
    estimatedComplexity: 'complex',
    estimatedLaunchTime: '3–4 weeks',
    description: 'Authenticated client portal for managing projects, documents, approvals, and payments in one place.',
  },

  // ── SAAS ────────────────────────────────────────────────────
  {
    id: 'template-saas',
    name: 'SaaS Product Dashboard',
    category: 'saas',
    bestFor: 'Software products with user accounts and data',
    requiredPages: ['Landing', 'Login', 'Dashboard', 'Analytics', 'Settings'],
    defaultSections: ['Feature showcase', 'Pricing', 'Analytics panels', 'Team management', 'Data export'],
    ctaStrategy: 'Sign up free or start trial',
    leadFields: ['Email', 'Company', 'Industry'],
    validationChecks: ['Login works', 'Data loads', 'Export functions', 'UI responsive'],
    socialAssets: ['Feature screenshots', 'Dashboard preview', 'Data visualization'],
    recommendedWorkflow: 'full-client-portal',
    estimatedComplexity: 'complex',
    estimatedLaunchTime: '4–6 weeks',
    description: 'Full SaaS landing page + app dashboard with user management, analytics panels, and team collaboration.',
  },

  // ── FUNNEL ─────────────────────────────────────────────────
  {
    id: 'template-funnel',
    name: 'High-Converting Sales Funnel',
    category: 'funnel',
    bestFor: 'Products or services with a multi-step sales process',
    requiredPages: ['Landing', 'Product', 'Checkout', 'Confirmation'],
    defaultSections: ['Hook', 'Problem + Agitation', 'Solution', 'Objections', 'Proof', 'Urgency', 'CTA'],
    ctaStrategy: 'Add to cart, checkout, or purchase',
    leadFields: ['Email', 'Payment info'],
    validationChecks: ['Cart functions', 'Checkout secure', 'Email confirmation sends', 'Thank you page loads'],
    socialAssets: ['Product images', 'Testimonial graphics', 'Scarcity elements'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'complex',
    estimatedLaunchTime: '2–3 weeks',
    description: 'Proven multi-step sales funnel with psychological triggers, objection handling, and seamless checkout.',
  },

  // ── ESTIMATE ───────────────────────────────────────────────
  {
    id: 'template-estimate',
    name: 'Estimate & Quote System',
    category: 'estimate',
    bestFor: 'Businesses that provide custom quotes',
    requiredPages: ['Home', 'Quote Request', 'Dashboard', 'Quote View'],
    defaultSections: ['Service options', 'Customization form', 'Real-time calculator', 'Quote display', 'Share/download'],
    ctaStrategy: 'Generate and download quote',
    leadFields: ['Name', 'Email', 'Phone', 'Project details'],
    validationChecks: ['Form validation', 'PDF generation', 'Email delivery', 'Dashboard access'],
    socialAssets: ['Quote template', 'Service icons'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '2–3 weeks',
    description: 'Interactive quote system that generates, emails, and tracks custom estimates — eliminating phone-tag.',
  },

  // ── AI CONSULTING ──────────────────────────────────────────
  {
    id: 'template-ai',
    name: 'AI Consulting Site',
    category: 'ai-consulting',
    bestFor: 'AI consultants and implementation experts',
    requiredPages: ['Home', 'Services', 'Insights', 'Case Studies', 'Contact'],
    defaultSections: ['AI value prop', 'Service tiers', 'Blog/insights', 'Client results', 'Expert team', 'CTA'],
    ctaStrategy: 'Book consultation or strategy call',
    leadFields: ['Name', 'Email', 'Company', 'AI Interest'],
    validationChecks: ['All content loads', 'Scheduling works', 'Blog posts display', 'Mobile responsive'],
    socialAssets: ['Concept graphics', 'Data visualizations', 'Team headshots'],
    recommendedWorkflow: 'estimate-approval-flow',
    estimatedComplexity: 'moderate',
    estimatedLaunchTime: '2–3 weeks',
    description: 'Authority-building website for AI consultants to showcase expertise, publish insights, and attract enterprise clients.',
  },

  // ── E-COMMERCE ─────────────────────────────────────────────
  {
    id: 'template-ecommerce',
    name: 'E-Commerce Starter',
    category: 'ecommerce',
    bestFor: 'Selling physical or digital products online',
    requiredPages: ['Catalog', 'Product Detail', 'Cart', 'Checkout', 'Orders'],
    defaultSections: ['Product grid', 'Filters', 'Product detail', 'Reviews', 'Related products', 'Cart/checkout'],
    ctaStrategy: 'Add to cart and purchase',
    leadFields: ['Email', 'Shipping address', 'Payment info'],
    validationChecks: ['Product search works', 'Cart persists', 'Payment processes', 'Order confirmation'],
    socialAssets: ['Product photos', 'Category images', 'Promo banners'],
    recommendedWorkflow: 'full-client-portal',
    estimatedComplexity: 'complex',
    estimatedLaunchTime: '3–4 weeks',
    description: 'Full e-commerce store with product catalog, cart, checkout, and order management.',
  },

  // ── DASHBOARD ──────────────────────────────────────────────
  {
    id: 'template-dashboard',
    name: 'Internal Ops Dashboard',
    category: 'dashboard',
    bestFor: 'Internal team tools and operations dashboards',
    requiredPages: ['Dashboard', 'Reports', 'Team', 'Settings', 'Integrations'],
    defaultSections: ['KPI cards', 'Charts/graphs', 'Data tables', 'Task lists', 'Team collaboration'],
    ctaStrategy: 'Action within dashboard (create task, assign, update)',
    leadFields: [],
    validationChecks: ['Data loads correctly', 'Filters work', 'Export functions', 'Notifications'],
    socialAssets: [],
    recommendedWorkflow: 'full-client-portal',
    estimatedComplexity: 'complex',
    estimatedLaunchTime: '3–4 weeks',
    description: 'Internal command center for teams to track KPIs, manage tasks, and collaborate on operations.',
  },
]

export const PLAYBOOKS: Playbook[] = [
  {
    id: 'playbook-flooring',
    industry: 'Flooring & Polishing',
    idealBuyer: 'Homeowner or commercial property manager needing floor installation or restoration',
    commonPainPoints: ['Stained or damaged concrete', 'Ugly floors hurting property value', 'Can\'t find a reliable installer', 'Don\'t know cost upfront'],
    strongestOffers: ['Free on-site estimate', 'Before/after guarantee', 'Lifetime stain warranty', 'Same-week availability'],
    recommendedWebsiteType: 'Flooring & Polishing Company template',
    recommendedLeadMagnet: 'Free on-site floor inspection and estimate',
    trustProofRequired: ['Before/after photo gallery', 'Google/Yelp reviews', 'Years in business', 'Product certifications'],
    commonObjections: ['How much will it cost?', 'How long does it take?', 'Will it hold up?', 'Can you match my style?'],
    highConvertingCtas: ['Get Free Floor Estimate', 'See Our Work', 'Call for Same-Week Service'],
    recommendedPages: ['Home', 'Flooring Systems', 'Gallery', 'Service Areas', 'Testimonials', 'Free Quote'],
    validationTests: ['Mobile click-to-call', 'Gallery loads on mobile', 'Quote form submits', 'Service areas accurate'],
    launchPostIdeas: ['Before/after transformation reel', 'Floor type comparison post', 'Service area announcement', 'Customer success story'],
    description: 'Playbook for epoxy flooring, concrete polishing, and floor coating contractors',
  },
  {
    id: 'playbook-home-services',
    industry: 'Home Services',
    idealBuyer: 'Homeowner with an urgent or seasonal service need',
    commonPainPoints: ['Finding a reliable contractor', 'Trust in quality', 'Price transparency', 'Scheduling flexibility'],
    strongestOffers: ['Free inspection', 'Same-day service', 'Warranty/guarantee', 'Transparent pricing'],
    recommendedWebsiteType: 'Local Service Website',
    recommendedLeadMagnet: 'Free inspection or estimate',
    trustProofRequired: ['Before/after photos', 'Customer testimonials', 'Years in business', 'Licenses/certifications'],
    commonObjections: ['Too expensive', 'How do I know you\'re reliable?', 'Can you do it this week?'],
    highConvertingCtas: ['Get Free Inspection', 'Schedule Now', 'Call for Same-Day Service'],
    recommendedPages: ['Home', 'Services', 'Service Areas', 'Portfolio', 'Testimonials', 'Contact'],
    validationTests: ['Mobile click-to-call', 'Mobile form submission', 'Service area accuracy', 'Response time'],
    launchPostIdeas: ['Show before/after', 'Team member intro', 'Common problems solved', 'New service launch'],
    description: 'Playbook for home service contractors selling locally',
  },
  {
    id: 'playbook-roofing',
    industry: 'Roofing',
    idealBuyer: 'Homeowner dealing with storm damage, leak, or aging roof',
    commonPainPoints: ['Roof leak causing damage', 'Insurance claim confusion', 'Finding trustworthy roofer', 'Price uncertainty'],
    strongestOffers: ['Free storm damage inspection', 'Insurance claim assistance', 'Lifetime warranty shingles', 'Same-week scheduling'],
    recommendedWebsiteType: 'Roofing Contractor Website',
    recommendedLeadMagnet: 'Free roof inspection and damage report',
    trustProofRequired: ['GAF/Owens Corning certifications', 'Insurance work history', 'Customer reviews', 'Before/after photos'],
    commonObjections: ['My insurance won\'t cover it', 'How long will it take?', 'Are you licensed and insured?'],
    highConvertingCtas: ['Schedule Free Inspection', 'Get Insurance Help', 'Call 24/7 Emergency'],
    recommendedPages: ['Home', 'Roofing Services', 'Insurance Claims', 'Service Areas', 'Reviews', 'Free Inspection'],
    validationTests: ['Emergency number prominent', 'Insurance page accurate', 'Inspection form submits', 'Mobile first'],
    launchPostIdeas: ['Storm season warning post', 'Insurance claim walkthrough', 'Certification announcement', 'Customer roof reveal'],
    description: 'Playbook for residential and commercial roofing contractors',
  },
  {
    id: 'playbook-hvac',
    industry: 'HVAC & Plumbing',
    idealBuyer: 'Homeowner or building manager with equipment failure or maintenance need',
    commonPainPoints: ['AC/heat broken during extreme weather', 'High utility bills', 'Unreliable service', 'Emergency repairs'],
    strongestOffers: ['24/7 emergency service', 'Maintenance plans', 'Financing options', 'Same-day service guarantee'],
    recommendedWebsiteType: 'HVAC & Mechanical Services',
    recommendedLeadMagnet: 'Free system inspection or maintenance check',
    trustProofRequired: ['NATE certification', 'Insurance verification', 'Customer reviews', 'Years in business'],
    commonObjections: ['Too expensive', 'Already have a contractor', 'Can\'t get here fast enough'],
    highConvertingCtas: ['Call 24/7 Emergency', 'Schedule Maintenance', 'Get Free System Check'],
    recommendedPages: ['Home', 'Services', 'Maintenance Plans', 'Emergency Service', 'Service Areas', 'Contact'],
    validationTests: ['24/7 number prominent', 'Emergency page works', 'Maintenance plan displayed', 'Mobile call button'],
    launchPostIdeas: ['Seasonal tune-up reminder', 'Emergency response story', 'Energy saving tips', 'Maintenance plan launch'],
    description: 'Playbook for HVAC, plumbing, and mechanical service contractors',
  },
  {
    id: 'playbook-medical',
    industry: 'Medical & Aesthetics',
    idealBuyer: 'Person concerned with appearance, health, or body improvement',
    commonPainPoints: ['Safety concerns', 'Result guarantees', 'Cost', 'Confidentiality'],
    strongestOffers: ['Free consultation', 'Results guarantee', 'Financing options', 'Expert credentials'],
    recommendedWebsiteType: 'Premium Business Website',
    recommendedLeadMagnet: 'Free consultation booking',
    trustProofRequired: ['Provider credentials', 'Before/after results', 'Patient testimonials', 'Safety certifications'],
    commonObjections: ['Is it safe?', 'Will it look natural?', 'How much does it cost?', 'What\'s the recovery time?'],
    highConvertingCtas: ['Book Free Consultation', 'View Results', 'Schedule Your Appointment'],
    recommendedPages: ['Home', 'Procedures', 'Provider', 'Before/After Gallery', 'FAQ', 'Contact'],
    validationTests: ['FAQ completeness', 'Booking system works', 'Gallery displays properly', 'Mobile responsive'],
    launchPostIdeas: ['Provider introduction', 'Patient success story', 'Procedure overview', 'Safety commitment'],
    description: 'Playbook for medical spas, aesthetics, and elective medical service providers',
  },
  {
    id: 'playbook-legal',
    industry: 'Legal & Professional Services',
    idealBuyer: 'Person with a legal problem needing expert representation',
    commonPainPoints: ['Finding right attorney', 'Cost uncertainty', 'Complex information', 'Privacy concerns'],
    strongestOffers: ['Free consultation', 'No upfront fees', 'Clear pricing', 'Specialist expertise'],
    recommendedWebsiteType: 'Premium Business Website',
    recommendedLeadMagnet: 'Free legal consultation',
    trustProofRequired: ['Attorney credentials', 'Case results', 'Years of experience', 'Bar membership'],
    commonObjections: ['How much will this cost?', 'How long will this take?', 'Do I have a case?'],
    highConvertingCtas: ['Schedule Free Consultation', 'Get Legal Help Now', 'Call for Expert Advice'],
    recommendedPages: ['Home', 'Practice Areas', 'Attorneys', 'Resources', 'FAQ', 'Contact'],
    validationTests: ['Form submission', 'CTA prominence', 'FAQ helpful', 'Easy contact options'],
    launchPostIdeas: ['Legal tips article', 'Case study (anonymized)', 'Attorney bio', 'Client success'],
    description: 'Playbook for lawyers, legal firms, and professional service providers',
  },
  {
    id: 'playbook-ai-consulting',
    industry: 'AI Consulting',
    idealBuyer: 'Business leader wanting to implement AI for competitive advantage',
    commonPainPoints: ['Understanding AI capabilities', 'ROI uncertainty', 'Implementation complexity', 'Data privacy'],
    strongestOffers: ['Free AI strategy call', 'ROI analysis', 'Phased implementation', 'Training included'],
    recommendedWebsiteType: 'AI Consulting Site',
    recommendedLeadMagnet: 'Free AI strategy assessment',
    trustProofRequired: ['Case studies with results', 'Client testimonials', 'AI expertise proof', 'Industry experience'],
    commonObjections: ['We don\'t understand AI', 'Too expensive', 'Too risky', 'Not for our industry'],
    highConvertingCtas: ['Get Free AI Strategy', 'Schedule Consultation', 'Calculate Your AI ROI'],
    recommendedPages: ['Home', 'Services', 'Case Studies', 'Blog', 'Team', 'Contact'],
    validationTests: ['Case studies compelling', 'CTA clear', 'Contact form works', 'Mobile friendly'],
    launchPostIdeas: ['AI trend analysis', 'Implementation case study', 'Team expertise', 'Industry AI insights'],
    description: 'Playbook for AI consultants and implementation partners',
  },
  {
    id: 'playbook-real-estate',
    industry: 'Real Estate',
    idealBuyer: 'Home buyer, seller, or investor looking for expert guidance',
    commonPainPoints: ['Finding right property', 'Trusting agent', 'Market information', 'Time to sell/buy'],
    strongestOffers: ['Free market analysis', 'Exclusive listings', 'Fast turnaround', 'Expert negotiation'],
    recommendedWebsiteType: 'Local Service Website',
    recommendedLeadMagnet: 'Free home valuation',
    trustProofRequired: ['Sold listings', 'Testimonials', 'Market expertise', 'Response speed'],
    commonObjections: ['Why your agent?', 'Will you get me the best price?', 'How fast can you sell?'],
    highConvertingCtas: ['Get Your Home Valued', 'View Listings', 'Schedule Showing'],
    recommendedPages: ['Home', 'Listings', 'About Agent', 'Testimonials', 'Market Reports', 'Contact'],
    validationTests: ['Search functionality', 'Property details load', 'Contact forms work', 'Mobile responsive'],
    launchPostIdeas: ['Market report', 'New listing reveal', 'Sold success story', 'Neighborhood guide'],
    description: 'Playbook for real estate agents and brokers',
  },
  {
    id: 'playbook-coaching',
    industry: 'Coaching & Education',
    idealBuyer: 'Professional seeking transformation, skill development, or accountability',
    commonPainPoints: ['Finding quality coach', 'Proving ROI', 'Cost justification', 'Time commitment'],
    strongestOffers: ['Results guarantee', 'Money-back guarantee', 'Free assessment', 'Personal attention'],
    recommendedWebsiteType: 'Premium Business Website',
    recommendedLeadMagnet: 'Free discovery call or assessment',
    trustProofRequired: ['Student success stories', 'Credentials', 'Testimonials', 'Case studies'],
    commonObjections: ['Does it really work?', 'Is it worth the price?', 'How much time?', 'Am I capable?'],
    highConvertingCtas: ['Start Free Assessment', 'Book Discovery Call', 'Enroll Now'],
    recommendedPages: ['Home', 'Programs', 'About Coach', 'Student Results', 'FAQ', 'Contact'],
    validationTests: ['Video testimonials play', 'Booking system works', 'FAQ comprehensive', 'Clear pricing'],
    launchPostIdeas: ['Student transformation', 'Coaching methodology', 'Success metrics', 'FAQ answers'],
    description: 'Playbook for coaches, trainers, and online educators',
  },
  {
    id: 'playbook-restaurant',
    industry: 'Restaurant & Food Service',
    idealBuyer: 'Local customer looking for dining, catering, or food delivery',
    commonPainPoints: ['Finding reliable dining option', 'Menu variety', 'Online ordering', 'Event catering'],
    strongestOffers: ['Online ordering', 'Catering packages', 'Loyalty program', 'Special menus'],
    recommendedWebsiteType: 'Local Service Website',
    recommendedLeadMagnet: 'First-order discount or free delivery',
    trustProofRequired: ['Food photos', 'Google reviews', 'Health certifications', 'Media mentions'],
    commonObjections: ['Is it fresh?', 'Can you accommodate allergies?', 'What\'s the wait time?'],
    highConvertingCtas: ['Order Online Now', 'Reserve a Table', 'Book Catering'],
    recommendedPages: ['Home', 'Menu', 'Order Online', 'Catering', 'About', 'Contact'],
    validationTests: ['Online order flow', 'Menu displays correctly', 'Reservation system works', 'Mobile photos load'],
    launchPostIdeas: ['Dish of the day', 'Behind-the-scenes kitchen', 'Event catering promo', 'Customer feature'],
    description: 'Playbook for restaurants, cafes, food trucks, and catering companies',
  },
  {
    id: 'playbook-fitness',
    industry: 'Fitness & Wellness',
    idealBuyer: 'Person wanting to improve health, lose weight, or build strength',
    commonPainPoints: ['Motivation and accountability', 'Finding time to train', 'Not seeing results', 'Intimidated by gyms'],
    strongestOffers: ['Free trial class', 'Money-back guarantee', '1-on-1 coaching', 'Online programs'],
    recommendedWebsiteType: 'Premium Business Website',
    recommendedLeadMagnet: 'Free assessment or trial class',
    trustProofRequired: ['Transformation photos', 'Trainer credentials', 'Member testimonials', 'Results data'],
    commonObjections: ['I don\'t have time', 'It won\'t work for me', 'Too expensive', 'I\'m a beginner'],
    highConvertingCtas: ['Claim Free Trial Class', 'Book Assessment', 'Start Your Transformation'],
    recommendedPages: ['Home', 'Programs', 'Trainers', 'Results', 'Schedule', 'Join Now'],
    validationTests: ['Schedule page works', 'Sign up flow smooth', 'Video testimonials play', 'Mobile friendly'],
    launchPostIdeas: ['Member transformation', 'Trainer profile', 'Program launch', 'Challenge announcement'],
    description: 'Playbook for gyms, personal trainers, yoga studios, and wellness centers',
  },
  {
    id: 'playbook-landscaping',
    industry: 'Landscaping & Outdoor',
    idealBuyer: 'Homeowner wanting a beautiful, low-maintenance outdoor space',
    commonPainPoints: ['Yard looks bad', 'No time for maintenance', 'Not sure what\'s possible', 'Price transparency'],
    strongestOffers: ['Free landscape design consult', 'Seasonal maintenance plans', 'Before/after guarantee', 'Financing'],
    recommendedWebsiteType: 'Landscaping & Outdoor Living',
    recommendedLeadMagnet: 'Free landscape design consultation',
    trustProofRequired: ['Before/after portfolio', 'Customer reviews', 'Design awards', 'Certifications'],
    commonObjections: ['How much will it cost?', 'How long until it looks good?', 'Will plants survive?'],
    highConvertingCtas: ['Get Free Design Consult', 'See Our Work', 'Schedule Service'],
    recommendedPages: ['Home', 'Services', 'Portfolio', 'Seasonal Specials', 'Service Areas', 'Free Quote'],
    validationTests: ['Portfolio loads', 'Quote form submits', 'Service areas accurate', 'Mobile images'],
    launchPostIdeas: ['Seasonal transformation', 'Design tip post', 'New service announcement', 'Customer reveal'],
    description: 'Playbook for landscaping, lawn care, and outdoor living contractors',
  },
]

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find(t => t.id === id)
}

export function getPlaybook(id: string): Playbook | undefined {
  return PLAYBOOKS.find(p => p.id === id)
}

export function getTemplatesByCategory(category: Template['category']): Template[] {
  return TEMPLATES.filter(t => t.category === category)
}

export function getPlaybookByIndustry(industry: string): Playbook | undefined {
  return PLAYBOOKS.find(p => p.industry.toLowerCase() === industry.toLowerCase())
}
