'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import type { AutonomousBuild } from '@/lib/autonomy/types';

export default function AutonomyPage() {
  const [builds,setBuilds]=useState<AutonomousBuild[]>([]);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const load=useCallback(async()=>{const r=await fetch('/api/autonomy/builds?limit=100',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load builds');setBuilds(d.builds||[])},[]);
  useEffect(()=>{load().catch(e=>setError(String(e)));const t=setInterval(()=>load().catch(()=>{}),10000);return()=>clearInterval(t)},[load]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const title=String(form.get('title')||'').trim();const mission=String(form.get('mission')||'').trim();try{const r=await fetch('/api/autonomy/builds',{method:'POST',headers:{'Content-Type':'application/json','x-idempotency-key':`dashboard:${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}:${Date.now()}`},body:JSON.stringify({title,mission,browserMode:form.get('browserMode'),maxConcurrency:Number(form.get('maxConcurrency')||8),requestedOutputs:['github_repo','vercel_project','validated_preview']})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Submission failed');e.currentTarget.reset();await load()}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
  async function control(id:string,action:'cancel'|'retry'){await fetch(`/api/autonomy/builds/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});await load()}
  return <main className="min-h-screen bg-zinc-950 text-white p-6 md:p-10"><div className="mx-auto max-w-7xl space-y-8"><header><p className="text-xs tracking-[.28em] text-emerald-400 uppercase">AUTOBUILDER-V2</p><h1 className="text-3xl md:text-5xl font-black mt-2">Controlled Autonomy</h1><p className="text-zinc-400 mt-3 max-w-3xl">Submit the mission once. Durable workers handle ingestion, parallel agents, browser execution, GitHub, Vercel, validation, repair, and completion evidence.</p></header>
  <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-zinc-800 bg-zinc-900/70 p-5"><input name="title" required placeholder="Project title" className="rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><textarea name="mission" required placeholder="Describe the complete system to build" rows={5} className="rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><div className="flex flex-wrap gap-3"><select name="browserMode" defaultValue="auto" className="rounded-lg bg-zinc-950 border border-zinc-700 p-3"><option value="auto">Automatic browser mode</option><option value="headless">Headless</option><option value="headful">Headful with takeover</option></select><input name="maxConcurrency" type="number" min="1" max="32" defaultValue="8" className="w-40 rounded-lg bg-zinc-950 border border-zinc-700 p-3"/><button disabled={busy} className="rounded-lg bg-emerald-400 px-5 py-3 font-bold text-black disabled:opacity-50">{busy?'Submitting…':'Launch Autonomous Build'}</button></div>{error&&<p className="text-red-400">{error}</p>}</form>
  <section className="grid gap-4">{builds.map(b=><article key={b.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{b.title}</h2><p className="text-xs text-zinc-500 mt-1">{b.id}</p></div><span className="h-fit rounded-full border border-zinc-700 px-3 py-1 text-sm">{b.status} · {b.current_stage}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full bg-emerald-400" style={{width:`${b.progress}%`}}/></div><div className="mt-4 grid gap-2 text-sm md:grid-cols-2"><p>Progress: <b>{b.progress}%</b></p><p>Retries: <b>{b.retry_count}</b></p>{b.github_repo_url&&<a className="text-sky-400" href={b.github_repo_url} target="_blank">GitHub repository</a>}{b.github_pr_url&&<a className="text-sky-400" href={b.github_pr_url} target="_blank">Pull request</a>}{b.preview_url&&<a className="text-emerald-400" href={b.preview_url} target="_blank">Validated preview</a>}{typeof b.validation_score==='number'&&<p>Validation: <b>{b.validation_score}%</b></p>}</div>{b.last_error&&<p className="mt-3 rounded-lg bg-red-950/40 p-3 text-sm text-red-300">{b.last_error}</p>}<div className="mt-4 flex gap-2">{!['COMPLETE','CANCELLED'].includes(b.status)&&<button onClick={()=>control(b.id,'cancel')} className="rounded border border-zinc-700 px-3 py-2 text-sm">Cancel</button>}{['FAILED','CANCELLED','NEEDS_INPUT'].includes(b.status)&&<button onClick={()=>control(b.id,'retry')} className="rounded bg-white px-3 py-2 text-sm font-bold text-black">Retry</button>}</div></article>)}{builds.length===0&&<div className="rounded-2xl border border-dashed border-zinc-700 p-12 text-center text-zinc-500">No autonomous builds yet.</div>}</section></div></main>
}
